version: '3.8'

services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./grant_all.sql:/docker-entrypoint-initdb.d/privileges.sql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    ports:
      - 3316:3306

  web:
    container_name: drf-api
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    ports:
      - 8888:8888
    depends_on:
      - db
    links:
      - db
